### ISSUE TITLE
My Username and Pass True But Error

### ISSUE THREAD

**Issue by virgilpostell** [n3s7or/symfonycasts-scraper#9]
`E:\symfonycasts-scraper-master>scraper.py --course symfony4
Traceback (most recent call last):
  File "E:\symfonycasts-scraper-master\scraper.py", line 21, in <module>
    main()
  File "E:\symfonycasts-scraper-master\scraper.py", line 16, in main
    for direct_link in symfonycasts.get_direct_links():
  File "E:\symfonycasts-scraper-master\sycs\SimpleSymfonycastsScraper.py", line 39, in get_direct_links
    self.__authenticate()
  File "E:\symfonycasts-scraper-master\sycs\SimpleSymfonycastsScraper.py", line 74, in __authenticate
    raise Exception('Invalid username or pass.')
Exception: Invalid username or pass.`

**Comment by n3s7or** [comment]
If you setted your credentials with quotes, try setting them without quotes:

```
set SCS_USER=testuser@gmail.com
set SCS_PASS=T3s7U$erPass123*
```
